/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "bg-primary": "#0a0a0f",
        "bg-secondary": "#111827",
        "bg-tertiary": "#1f2937",
        "surface-primary": "#1a1a24",
        "surface-secondary": "#2d2d3a",
        "surface-elevated": "#3a3a4a",
        "primary-main": "#fbbf24",
        "primary-light": "#fcd34d",
        "primary-dark": "#f59e0b",
        "primary-darker": "#d97706",
        "text-primary": "#fef3c7",
        "text-secondary": "#fde68a",
        "text-tertiary": "#9ca3af",
        "text-accent": "#fbbf24",
        "border-primary": "#374151",
        "border-secondary": "#4b5563",
        "border-accent": "#fbbf24",
        "border-subtle": "#2d3748",
        success: "#fbbf24",
        overlay: "rgba(0, 0, 0, 0.85)",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        lg: "18px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "30px",
        "4xl": "36px",
        "5xl": "48px",
        "6xl": "60px",
        "7xl": "72px",
        "8xl": "96px",
        "9xl": "128px",
      },
      boxShadow: {
        glow: "0 0 20px rgba(251, 191, 36, 0.6)",
        "glow-strong": "0 0 30px rgba(251, 191, 36, 0.8)",
        "glow-subtle": "0 0 15px rgba(251, 191, 36, 0.3)",
      },
    },
  },
  plugins: [],
};
