/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all files that contain Nativewind classes.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "bg-primary": "#0a1410",
        "bg-secondary": "#0f1e1a",
        "bg-tertiary": "#1a2e27",
        "surface-primary": "#152820",
        "surface-secondary": "#1f3a2f",
        "surface-elevated": "#2a4a3c",
        "primary-main": "#10b981",
        "primary-light": "#34d399",
        "primary-dark": "#059669",
        "primary-darker": "#047857",
        "text-primary": "#d1fae5",
        "text-secondary": "#a7f3d0",
        "text-tertiary": "#6ee7b7",
        "text-accent": "#10b981",
        "border-primary": "#2a4a3c",
        "border-secondary": "#34d399",
        "border-accent": "#10b981",
        "border-subtle": "#1f3a2f",
        success: "#10b981",
        overlay: "rgba(10, 20, 16, 0.85)",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        xxl: "48px",
      },
      borderRadius: {
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
      },
      fontSize: {
        xs: "12px",
        sm: "14px",
        base: "16px",
        lg: "18px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "30px",
        "4xl": "36px",
        "5xl": "48px",
        "6xl": "60px",
        "7xl": "72px",
        "8xl": "96px",
        "9xl": "128px",
      },
      boxShadow: {
        glow: "0 0 20px rgba(16, 185, 129, 0.6)",
        "glow-strong": "0 0 30px rgba(16, 185, 129, 0.8)",
        "glow-subtle": "0 0 15px rgba(16, 185, 129, 0.3)",
      },
    },
  },
  plugins: [],
};
